### ISSUE TITLE
Can you give me access to https://dbsystems-engproject.rhcloud.com

### ISSUE THREAD

**Issue by arshadalisoomro** [klinker24/conference_room_scheduler#1]
Hi there I'm so excited from your work on githut.com and I want to see a demo of this website can you please tell me how may I tour your this project in action https://dbsystems-engproject.rhcloud.com.
Thanks

**Comment by klinker24** [comment]
There are a number of generic users you can log in with.

admin@test.com
manager@test.com
user@test.com

The password for all of them is just: password1

Sorry to disappoint though, this website isn't much of anything unfortunately. Just a simple school project that a team and I had to set up for a databases class
